<?php
define('SERVEUR','nohain');
define('BASE','PROSERVIA');
define('USER','RHODON');
define('PASSWD','ztDT#323YsaIcVJ');//rhodon%44
define('CEGID_SERVEUR','chezine');
define('CEGID_BASE','PROSERVIA');
define('CEGID_USER','srvintra');
define('CEGID_PASSWD','SXtGNNpk4NNsUc8');
define('CVWEB_SERVEUR','proservia.systonic.net');
define('CVWEB_PORTSSH','2222');
define('CVWEB_BASE','candidature');
define('CVWEB_USER','remoteuser');
define('CVWEB_PASSWD','CXM1Wh8vtdGcyhaASvAB');
/*define('SF_USER','mathieu.perrin@proservia.fr.integrale');
define('SF_PASSWD','SFCPro44');
define('SF_TOKEN','rNVVhlZ5wEQwGAcpvyQ1qr0P'); 
define('SF_USER','etude.dev@proservia.fr.integrale');
define('SF_PASSWD','SFCPro44');
define('SF_TOKEN','zYyLQFsEpWxPeQd9ius179A5x');
 */
define('SF_USER','api@proservia.fr');
define('SF_PASSWD','c8fruJ@kECrepemUFE');
define('SF_TOKEN','');
define('TALEO_USER','webservice');
define('TALEO_PASSWD','@DSIta1eO');
define('RIGHT_RJO_USER','super@right.com');
define('RIGHT_RJO_PASSWD','supersuper');
?>